### ISSUE TITLE
ModuleNotFoundError: No module named 'sketchgraphs.data'

### ISSUE THREAD

**Issue by v4r4rth** [PrincetonLIPS/vitruvion#6]
Hi, thank you for this really interesting project! I was hoping for some assistance..

I have downloaded all the required files into the project but have been unable to inference with the models.

Could you please providea step by step tutorial to help transform an input sketch (hand drawn image) to the network for obtaining either a vector or a CAD file? 

For the mentioned error, here is the terminal log -

```

(vitruvion) sid@e2e-62-76:~/vitruvion/vitruvion$ ./start_singularity.sh python -m img2cad.evaluation.evaluate_image_to_primitive checkpoint_path=models/image_to_primitive.ckpt sequence_path=data/sg_filtered_unique.npy

=============
== PyTorch ==
=============

NVIDIA Release 21.03 (build 21060478)
PyTorch Version 1.9.0a0+df837d0

Container image Copyright (c) 2021, NVIDIA CORPORATION.  All rights reserved.

Copyright (c) 2014-2021 Facebook Inc.
Copyright (c) 2011-2014 Idiap Research Institute (Ronan Collobert)
Copyright (c) 2012-2014 Deepmind Technologies    (Koray Kavukcuoglu)
Copyright (c) 2011-2012 NEC Laboratories America (Koray Kavukcuoglu)
Copyright (c) 2011-2013 NYU                      (Clement Farabet)
Copyright (c) 2006-2010 NEC Laboratories America (Ronan Collobert, Leon Bottou, Iain Melvin, Jason Weston)
Copyright (c) 2006      Idiap Research Institute (Samy Bengio)
Copyright (c) 2001-2004 Idiap Research Institute (Ronan Collobert, Samy Bengio, Johnny Mariethoz)
Copyright (c) 2015      Google Inc.
Copyright (c) 2015      Yangqing Jia
Copyright (c) 2013-2016 The Caffe contributors
All rights reserved.

NVIDIA Deep Learning Profiler (dlprof) Copyright (c) 2021, NVIDIA CORPORATION.  All rights reserved.

Various files include modifications (c) NVIDIA CORPORATION.  All rights reserved.

This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license

NOTE: MOFED driver for multi-node communication was not detected.
      Multi-node communication performance may be reduced.

Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/sid/vitruvion/vitruvion/img2cad/evaluation/evaluate_image_to_primitive.py", line 18, in <module>
    from img2cad import dataset, primitives_data, primitives_models
  File "/home/sid/vitruvion/vitruvion/img2cad/dataset.py", line 28, in <module>
    import sketchgraphs.data as datalib
ModuleNotFoundError: No module named 'sketchgraphs.data'

```

Hope you can share a response soon, would appreciate being able to replicate this project.

Also curious - under what license has the project has been released? I cannot seem to find it in the description.

**Comment by kakaluote333** [comment]
Hi, do you still have the data for this paper? The link on the website is no longer working.
